version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      # The RDS endpoint should not include a protocol or trailing slash.
      WORDPRESS_DB_HOST: "${RDS_HOST}:3306"
      WORDPRESS_DB_USER: "${RDS_USER}"
      WORDPRESS_DB_PASSWORD: "${RDS_PASSWORD}"
      WORDPRESS_DB_NAME: "${RDS_DB_NAME}"
    volumes:
      # Mount a local directory to the container's web root (/var/www/html)
      ~/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      # Connect phpMyAdmin to the external RDS database.
      PMA_HOST: "${RDS_HOST}"
      PMA_PORT: "3306"
      # Enable arbitrary login mode so you can use any valid database credentials.
      PMA_ARBITRARY: "1"
