version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "${RDS_HOST}:3306"
      WORDPRESS_DB_USER: "${RDS_USER}"
      WORDPRESS_DB_PASSWORD: "${RDS_PASSWORD}"
      WORDPRESS_DB_NAME: "${RDS_DB_NAME}"
    volumes:
      - wordpress_data:/var/www/html/wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "${RDS_HOST}"
      PMA_PORT: "3306"
      PMA_ARBITRARY: "1"

volumes:
  wordpress_data:
